


var _DEPTH_BUFFER_BIT = 256;

var _STENCIL_BUFFER_BIT = 1024;

var _COLOR_BUFFER_BIT = 16384;

var _POINTS = 0;

var _LINES = 1;

var _LINE_LOOP = 2;

var _LINE_STRIP = 3;

var _TRIANGLES = 4;

var _TRIANGLE_STRIP = 5;

var _TRIANGLE_FAN = 6;

var _CULL_FACE = 2884;

var _BLEND = 3042;

var _DITHER = 3024;

var _STENCIL_TEST = 2960;

var _DEPTH_TEST = 2929;

var _SCISSOR_TEST = 3089;

var _POLYGON_OFFSET_FILL = 32823;

var _SAMPLE_ALPHA_TO_COVERAGE = 32926;

var _SAMPLE_COVERAGE = 32928;

var _ZERO = 0;

var _ONE = 1;

var _SRC_COLOR = 768;

var _ONE_MINUS_SRC_COLOR = 769;

var _SRC_ALPHA = 770;

var _ONE_MINUS_SRC_ALPHA = 771;

var _DST_ALPHA = 772;

var _ONE_MINUS_DST_ALPHA = 773;

var _BYTE = 5120;

var _UNSIGNED_BYTE = 5121;

var _SHORT = 5122;

var _UNSIGNED_SHORT = 5123;

var _INT = 5124;

var _UNSIGNED_INT = 5125;

var _FLOAT = 5126;

var _FRONT = 1028;

var _BACK = 1029;

var _FRONT_AND_BACK = 1032;

var _FRAGMENT_SHADER = 35632;

var _VERTEX_SHADER = 35633;

var _ARRAY_BUFFER = 34962;

var _ELEMENT_ARRAY_BUFFER = 34963;

var _ARRAY_BUFFER_BINDING = 34964;

var _ELEMENT_ARRAY_BUFFER_BINDING = 34965;

var _STREAM_DRAW = 35040;

var _STATIC_DRAW = 35044;

var _DYNAMIC_DRAW = 35048;

export {
  _DEPTH_BUFFER_BIT ,
  _STENCIL_BUFFER_BIT ,
  _COLOR_BUFFER_BIT ,
  _POINTS ,
  _LINES ,
  _LINE_LOOP ,
  _LINE_STRIP ,
  _TRIANGLES ,
  _TRIANGLE_STRIP ,
  _TRIANGLE_FAN ,
  _CULL_FACE ,
  _BLEND ,
  _DITHER ,
  _STENCIL_TEST ,
  _DEPTH_TEST ,
  _SCISSOR_TEST ,
  _POLYGON_OFFSET_FILL ,
  _SAMPLE_ALPHA_TO_COVERAGE ,
  _SAMPLE_COVERAGE ,
  _ZERO ,
  _ONE ,
  _SRC_COLOR ,
  _ONE_MINUS_SRC_COLOR ,
  _SRC_ALPHA ,
  _ONE_MINUS_SRC_ALPHA ,
  _DST_ALPHA ,
  _ONE_MINUS_DST_ALPHA ,
  _BYTE ,
  _UNSIGNED_BYTE ,
  _SHORT ,
  _UNSIGNED_SHORT ,
  _INT ,
  _UNSIGNED_INT ,
  _FLOAT ,
  _FRONT ,
  _BACK ,
  _FRONT_AND_BACK ,
  _FRAGMENT_SHADER ,
  _VERTEX_SHADER ,
  _ARRAY_BUFFER ,
  _ELEMENT_ARRAY_BUFFER ,
  _ARRAY_BUFFER_BINDING ,
  _ELEMENT_ARRAY_BUFFER_BINDING ,
  _STREAM_DRAW ,
  _STATIC_DRAW ,
  _DYNAMIC_DRAW ,
  
}
/* No side effect */
